Import(['env'])


src = [
]

srcLinted = [
    'Anzeige.c',
    'AnzeigeConfig.c',
]

include = [
    '#src/Anzeige'
]

env.Append(CPPPATH = include)


obj = env.Object(src)
env.Append(OBJECTS_BUILT = obj)

objLint = env.Object(srcLinted)
env.Append(OBJECTS_LINT_BUILT = objLint)




