Import(['env'])


src = [
    "FreeRtos/timers.c",
    'FreeRtos/tasks.c',
    'FreeRtos/stream_buffer.c',
    'FreeRtos/queue.c',
    'main.c',
    'FreeRtos/list.c',
    'FreeRtos/event_groups.c',
    'FreeRtos/croutine.c',
    'FreeRtos/port/heap_1.c',
    'FreeRtos/port/port.c'
]

srcLinted = [
]

include = [  '#src/OS',
            '#src/OS/FreeRtos',
            '#src/OS/FreeRtos/port',
            '#src/OS/FreeRtos/include'
]

env.Append(CPPPATH = include)


obj = env.Object(src)
env.Append(OBJECTS_BUILT = obj)

objLint = env.Object(srcLinted)
env.Append(OBJECTS_LINT_BUILT = objLint)
