Import(['env'])


src = [
    
]

srcLinted = [
    '02_Code/Fsm.c',
    '02_Code/Fsm_Ram.c',
]

include = [
    '#src/FiniteStateMachine/02_Code',
    '#src/FiniteStateMachine/03_Config',
]

env.Append(CPPPATH = include)

obj = env.Object(src)
env.Append(OBJECTS_BUILT = obj)

objLint = env.Object(srcLinted)
env.Append(OBJECTS_LINT_BUILT = objLint)
