Import(['env'])




SConscript(  [  'OS/SConscript',
                'Anzeige/SConscript',
                'LightSystem/SConscript',
                'commonIO/SConscript',
                'UART/SConscript',
                'adc/SConscript',
                'FiniteStateMachine/SConscript',
                'libs/SConscript'],
                    duplicate = 0,
                    exports = ['env']
                 )


src = [

]


# env.Append(CPPPATH = '#src/TimeKeeper')

localObjects = env.Object(src)

objs = []

objs.append(env['OBJECTS_BUILT'])
objs.append(env['OBJECTS_LINT_BUILT'])
objs.append(localObjects)

AddPreAction(env['OBJECTS_LINT_BUILT'],env["LINTCOM"])




# for debugging

# print(env.Dump('CCFLAGS'))
# print(env.Dump('CPPPATH'))
# print(env.Dump('LINKFLAGS'))
# print(env.Dump('ASFLAGS'))
# print(env.Dump('ASPPCOM'))
# print(env.Dump())
# print(env.Dump('toolpath'))
# print(env.Dump('PROG'))


target_name ='${TARGETNAME}'
TARGET_ELF = target_name + '.elf'
TARGET_HEX = target_name + '.hex'

env.Program(TARGET_ELF, objs)
# # Create hex binary file.
env.Hex(TARGET_HEX, TARGET_ELF)
# # Compute memory usage.
env.Size(None, TARGET_ELF)

if (env['PROG'] == 1):
    path = env['BUILDDIR'] + '/' + TARGET_HEX
    # path = TARGET_HEX
    env.Flash(path)

